/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unified geometric feature definition for assembly constraints (compatible with DTEditor Assembly Schema)
 */
export interface IGeometryFeature {
  /**
   * Feature type for assembly constraints
   */
  type: "Feature::Circle" | "Feature::Arc" | "Feature::Face" | "Feature::Plane" | "Feature::Point" | "Feature::Edge";
  /**
   * Feature name/identifier
   */
  name: string;
  /**
   * Position [x, y, z] - for point, cylinder, cone, torus
   */
  position?: [number, number, number];
  /**
   * Center point [x, y, z] - for sphere, circle, arc, face, plane
   */
  center?: [number, number, number];
  /**
   * Start point [x, y, z] - for edge, arc
   */
  start?: [number, number, number];
  /**
   * End point [x, y, z] - for edge, arc
   */
  end?: [number, number, number];
  /**
   * Direction axis [x, y, z] (normalized) - for cylinder, cone, torus
   */
  axis?: [number, number, number];
  /**
   * Normal vector [x, y, z] (normalized) - for circle, arc, face, plane
   */
  normal?: [number, number, number];
  /**
   * Radius - for cylinder, sphere, circle, arc
   */
  radius?: number;
  /**
   * Start angle in radians - for arc
   */
  startAngle?: number;
  /**
   * End angle in radians - for arc
   */
  endAngle?: number;
  /**
   * First/bottom radius - for cone
   */
  radius1?: number;
  /**
   * Second/top radius - for cone
   */
  radius2?: number;
  /**
   * Tube radius - for torus
   */
  tube?: number;
  /**
   * Height - for cylinder, cone
   */
  height?: number;
  /**
   * Bounding information - for face
   */
  bounds?: {
    [k: string]: any;
  };
  /**
   * Additional feature metadata (e.g., surfaceFinish, tolerance, fit, material)
   */
  metadata?: {
    [k: string]: any;
  };
}
