/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `IJCadContent`'s JSON-Schema
 * via the `definition` "parts".
 */
export type Parts =
  | "Part::Any"
  | "Part::Box"
  | "Part::Cylinder"
  | "Part::Sphere"
  | "Part::Cone"
  | "Part::Torus"
  | "Part::Cut"
  | "Part::MultiFuse"
  | "Part::MultiCommon"
  | "Part::Extrusion"
  | "Part::Chamfer"
  | "Part::Fillet"
  | "Sketcher::SketchObject"
  | "Post::Operator";
/**
 * This interface was referenced by `IJCadContent`'s JSON-Schema
 * via the `definition` "jcadModel".
 */
export type IJCadModel = IJCadObject[];

export interface IJCadContent {
  schemaVersion?: string;
  objects: IJCadModel;
  options?: IJCadOptions;
  metadata?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: string;
  };
  outputs?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: string;
  };
}
/**
 * This interface was referenced by `IJCadContent`'s JSON-Schema
 * via the `definition` "jcadObject".
 */
export interface IJCadObject {
  name: string;
  visible: boolean;
  shape?: Parts;
  parameters?: {
    [k: string]: any;
  };
  shapeMetadata?: IShapeMetadata;
  operators?: {
    [k: string]: any;
  }[];
  dependencies?: string[];
  /**
   * Assembly features extracted from this object (for DTEditor integration)
   */
  geometryFeatures?: IGeometryFeature[];
}
/**
 * This interface was referenced by `IJCadContent`'s JSON-Schema
 * via the `definition` "shapeMetadata".
 */
export interface IShapeMetadata {
  shapeFormat?: string;
  workerId?: string;
  mass?: number;
  centerOfMass?: number[];
  matrixOfInertia?: number[][];
}
/**
 * Unified geometric feature definition for assembly constraints (compatible with DTEditor Assembly Schema)
 *
 * This interface was referenced by `IJCadContent`'s JSON-Schema
 * via the `definition` "geometryFeature".
 */
export interface IGeometryFeature {
  /**
   * Feature type for assembly constraints
   */
  type: "Feature::Circle" | "Feature::Arc" | "Feature::Face" | "Feature::Plane" | "Feature::Point" | "Feature::Edge";
  /**
   * Feature name/identifier
   */
  name: string;
  /**
   * Position [x, y, z] - for point, cylinder, cone, torus
   */
  position?: [number, number, number];
  /**
   * Center point [x, y, z] - for sphere, circle, arc, face, plane
   */
  center?: [number, number, number];
  /**
   * Start point [x, y, z] - for edge, arc
   */
  start?: [number, number, number];
  /**
   * End point [x, y, z] - for edge, arc
   */
  end?: [number, number, number];
  /**
   * Direction axis [x, y, z] (normalized) - for cylinder, cone, torus
   */
  axis?: [number, number, number];
  /**
   * Normal vector [x, y, z] (normalized) - for circle, arc, face, plane
   */
  normal?: [number, number, number];
  /**
   * Radius - for cylinder, sphere, circle, arc
   */
  radius?: number;
  /**
   * Start angle in radians - for arc
   */
  startAngle?: number;
  /**
   * End angle in radians - for arc
   */
  endAngle?: number;
  /**
   * First/bottom radius - for cone
   */
  radius1?: number;
  /**
   * Second/top radius - for cone
   */
  radius2?: number;
  /**
   * Tube radius - for torus
   */
  tube?: number;
  /**
   * Height - for cylinder, cone
   */
  height?: number;
  /**
   * Bounding information - for face
   */
  bounds?: {
    [k: string]: any;
  };
  /**
   * Additional feature metadata (e.g., surfaceFinish, tolerance, fit, material)
   */
  metadata?: {
    [k: string]: any;
  };
}
/**
 * This interface was referenced by `IJCadContent`'s JSON-Schema
 * via the `definition` "jcadOptions".
 */
export interface IJCadOptions {}
